export const C = {
  GOODS_FETCH_SUCCESS: 'GOODS_FETCH_SUCCESS',
  GOODS_LOADING: 'GOODS_LOADING',
  GOODS_FILTER: 'GOODS_FILTER',
  GOODS_ERROR: 'GOODS_ERROR',
  FAVOURITES_FETCH_SUCCESS: 'FAVOURITES_FETCH_SUCCESS',
  FAVOURITES_FETCH_FAIL: 'FAVOURITES_FETCH_FAIL',
  FAVOURITES_ERROR: 'FAVOURITES_ERROR',
  FAVOURITES_ERROR_CLEAR: 'FAVOURITES_ERROR_CLEAR'
};