export const C = {
  STAFF_TABLE_FETCH_SUCCESS: 'STAFF_TABLE_FETCH_SUCCESS',
  STAFF_TABLE_LOADING: 'STAFF_TABLE_LOADING',
  STAFF_TABLE_ERROR: 'STAFF_TABLE_ERROR',
  STAFF_TABLE_FILTER: 'STAFF_TABLE_FILTER',
  STAFF_FILTER_SET_VALUE: 'STAFF_FILTER_SET_VALUE',
  STAFF_TABLE_EDIT_ROW: 'STAFF_TABLE_EDIT_ROW',
  STAFF_TABLE_DELETE_ROW: 'STAFF_TABLE_DELETE_ROW',
};